(function(){
    const loadUrl = document.getElementById('LoadGRNItemsUrl')?.value;
    const browseUrl = document.getElementById('BrowseGRNsUrl')?.value;
    const browseItemsUrl = document.getElementById('BrowseItemsForQualityRequestUrl')?.value;
    const browseBatchUrl = document.getElementById('BrowseBatchDetailsUrl')?.value;
    const createBatchUrl = document.getElementById('CreateBatchUrl')?.value;
    const saveUrl = (function(){ const el = document.getElementById('SaveQualityRequestUrl'); return el ? el.value : null; })();
    const deleteUrl = (function(){ const el=document.getElementById('DeleteQualityRequestUrl'); return el?el.value:null; })();

    let currentItemEditInput=null,currentBatchInput=null;
    let batchPage=0,batchPageSize=10; let grnPage=0,grnPageSize=10,grnTotal=0; let itemPage=0,itemPageSize=10,itemTotal=0;
    let batchWindow=null,pendingBatchRefresh=false;

    function createEmptyRow(){ const tr=document.createElement('tr'); tr.innerHTML=`<td><div class="input-group" style="width:150px;"><input class="form-control input input-sm" type="text" name="ItemCode" /><button type="button" class="btn btn-outline-secondary btn-sm" name="btnSearchItem"><i class="demo-pli-magnifi-glass"></i></button></div></td><td><input class="form-control input input-sm" type="text" name="ItemName" style="width:300px;" disabled/></td><td><input class="form-control input input-sm" type="text" name="BatchNo" style="width:150px;" /></td><td><input class="form-control input input-sm" type="text" name="Quantity" style="width:100px;" /></td><td><input class="form-control input input-sm" type="text" name="UOM" style="width:90px;" disabled/></td><td><input class="form-control input input-sm" type="text" name="ItemRemark" style="width:150px;" /></td><td hidden></td><td hidden></td><td hidden></td><td hidden></td><td><button type="button" class="btn btn-sm btn-danger btn-delete-line" disabled>X</button></td>`; return tr; }
    function ensureLastEmptyRow(){ const tbody=document.querySelector('#tblItemDetails tbody'); if(!tbody) return; const rows=tbody.querySelectorAll('tr'); if(rows.length===0){ tbody.appendChild(createEmptyRow()); return;} const last=rows[rows.length-1]; if(last.querySelector('input[name="ItemCode"]').value.trim()||last.querySelector('input[name="ItemName"]').value.trim()){ const newRow=createEmptyRow(); tbody.appendChild(newRow);} // enable delete buttons except last empty
        tbody.querySelectorAll('tr').forEach((r,i)=>{ const delBtn=r.querySelector('.btn-delete-line'); if(delBtn){ const isEmpty=!r.querySelector('input[name="ItemCode"]').value && !r.querySelector('input[name="ItemName"]').value && i===tbody.querySelectorAll('tr').length-1; delBtn.disabled=isEmpty; }});
    }
    function disableBatchNos(d){ document.querySelectorAll('#tblItemDetails tbody input[name="BatchNo"]').forEach(i=>i.disabled=!!d);}    
    function setItemsInGrid(items){ const tbody=document.querySelector('#tblItemDetails tbody'); if(!tbody) return; tbody.innerHTML=''; if(!items||!items.length){ tbody.appendChild(createEmptyRow()); disableBatchNos(false); ensureLastEmptyRow(); return;} items.forEach(it=>{ const tr=createEmptyRow(); tr.querySelector('input[name="ItemCode"]').value=it.Code||''; tr.querySelector('input[name="ItemName"]').value=it.Name||''; tr.querySelector('input[name="BatchNo"]').value=it.BatchNo||''; tr.querySelector('input[name="Quantity"]').value=(it.Quantity??''); tr.querySelector('input[name="UOM"]').value=(it.UOMSymbol||it.UOMName)||''; tr.children[6].textContent=it.GRNDetailId||''; tr.children[7].textContent=it.ItemId||''; tr.children[8].textContent=it.BatchId||''; tr.children[9].textContent=it.QualityRequestItemId||''; const delBtn=tr.querySelector('.btn-delete-line'); if(delBtn) delBtn.disabled=false; tbody.appendChild(tr); }); ensureLastEmptyRow(); }

    function loadGRNItems(grnId){ if(!loadUrl) return; const info=document.getElementById('mdlLoadInfo'); if(info) info.style.display='block'; fetch(loadUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},body:JSON.stringify({grnId:parseInt(grnId||0)})}).then(r=>r.json()).then(res=>{ if(info) info.style.display='none'; if(res && res.ExecutionResultId===1){ setItemsInGrid(res.data||[]); disableBatchNos(true);} else { setItemsInGrid([]); disableBatchNos(false);} }).catch(_=>{ if(info) info.style.display='none'; setItemsInGrid([]); disableBatchNos(false); }); }
    function formatMvcDate(v){ if(!v) return ''; if(typeof v==='string'&&/\d+/.test(v)){ const ms=parseInt(v.replace(/\D/g,''),10); if(!isNaN(ms)){ const d=new Date(ms); if(!isNaN(d.getTime())) return d.toISOString().slice(0,10);} } const d2=new Date(v); return isNaN(d2.getTime())?'':d2.toISOString().slice(0,10);}    

    function loadGRNList(){ if(!browseUrl) return; const tbody=document.querySelector('#tblGRNList tbody'); if(!tbody) return; tbody.innerHTML=''; const code=document.getElementById('txtGRNId')?.value||''; const payload={ start: grnPage*grnPageSize, length: grnPageSize, Code: code }; fetch(browseUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},body:JSON.stringify(payload)}).then(r=>r.json()).then(res=>{ const rows=res.data||[]; grnTotal=res.recordsTotal||rows.length; rows.forEach(row=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td style=display:none;>${row.GRNId}</td><td>${row.Code||''}</td><td>${formatMvcDate(row.GRNDate)}</td><td><button class='btn btn-sm btn-primary btn-pick-grn' data-id='${row.GRNId}' data-code='${row.Code||''}'>Pick</button></td>`; tbody.appendChild(tr); }); updateGrnPager(); }).catch(_=>{ grnTotal=0; updateGrnPager(); }); }
    function updateGrnPager(){ const totalPages=Math.ceil(grnTotal/grnPageSize)||0; const info=document.getElementById('grnPageInfo'); if(info) info.textContent= totalPages?`Page ${grnPage+1} of ${totalPages}`:'No results'; const prev=document.getElementById('btnGrnPrev'); const next=document.getElementById('btnGrnNext'); if(prev) prev.disabled=grnPage<=0; if(next) next.disabled=(grnPage+1)>=totalPages; }

    // Item modal paging
    function loadItemsForBrowse(){ if(!browseItemsUrl) return; const code=document.getElementById('mdlItemFilterCode')?.value||''; const name=document.getElementById('mdlItemFilterName')?.value||''; const tbody=document.querySelector('#tblItemBrowse tbody'); if(!tbody) return; tbody.innerHTML=''; const payload={ start:itemPage*itemPageSize, length:itemPageSize, Code:code, Name:name }; fetch(browseItemsUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest','X-QualityPlan-ItemBrowse':'1'},body:JSON.stringify(payload)}).then(r=>r.json()).then(res=>{ const rows=res.data||[]; itemTotal=res.recordsTotal||rows.length; rows.forEach(it=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${it.Code||''}</td><td>${it.Name||''}</td><td>${it.UOM||''}</td><td>${it.StockHandling||''}</td><td><button type='button' class='btn btn-sm btn-primary btn-pick-item'>Pick</button></td><td hidden>${it.ItemId||''}</td>`; tbody.appendChild(tr); }); updateItemPager(); }).catch(_=>{ itemTotal=0; updateItemPager(); }); }
    function updateItemPager(){ const info=document.getElementById('itemPageInfo'); const totalPages=Math.ceil(itemTotal/itemPageSize)||0; if(info) info.textContent= totalPages?`Page ${itemPage+1} of ${totalPages}`:'No results'; const prev=document.getElementById('btnItemPrev'); const next=document.getElementById('btnItemNext'); if(prev) prev.disabled=itemPage<=0; if(next) next.disabled=(itemPage+1)>=totalPages; }

    function openItemBrowse(inputEl){ currentItemEditInput=inputEl; itemPage=0; loadItemsForBrowse(); new bootstrap.Modal(document.getElementById('mdlSelectItem')).show(); }
    function openBatchBrowse(inputEl){ currentBatchInput=inputEl; batchPage=0; document.getElementById('mdlBatchFilterBatchNo').value=''; const funcMain=document.getElementById('FunctionId'); const funcModal=document.getElementById('mdlBatchFilterFunctionId'); if(funcMain&&funcModal){ funcModal.value=funcMain.value||'';} const row=inputEl.closest('tr'); document.getElementById('mdlBatchFilterItem').value=row.querySelector('input[name="ItemName"]').value||''; loadBatchPage(); new bootstrap.Modal(document.getElementById('mdlSelectBatch')).show(); }

    function loadBatchPage(){ if(!browseBatchUrl) return; const tbody=document.querySelector('#tblBatchBrowse tbody'); if(!tbody) return; tbody.innerHTML=''; const batchNo=document.getElementById('mdlBatchFilterBatchNo').value||''; const functionId=parseInt(document.getElementById('mdlBatchFilterFunctionId')?.value||'')||null; let itemId=null; if(currentBatchInput){ const row=currentBatchInput.closest('tr'); itemId=parseInt(row.children[7]?.textContent||'')||null; } const payload={ start: batchPage*batchPageSize, length: batchPageSize, BatchNo: batchNo, FunctionId: functionId, ItemId: itemId }; fetch(browseBatchUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},body:JSON.stringify(payload)}).then(r=>r.json()).then(res=>{ const rows=res.data||[]; const total=res.recordsTotal||rows.length; rows.forEach(b=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${b.BatchNo||''}</td><td>${b.CreatedDate||''}</td><td><button type='button' class='btn btn-sm btn-primary btn-pick-batch'>Pick</button></td><td hidden>${b.BatchId||''}</td>`; tbody.appendChild(tr); }); updateBatchPager(total); }).catch(_=>{ updateBatchPager(0); }); }
    function updateBatchPager(total){ const info=document.getElementById('batchPageInfo'); const totalPages=Math.ceil(total/batchPageSize)||0; if(info) info.textContent= totalPages?`Page ${batchPage+1} of ${totalPages}`:'No results'; const prev=document.getElementById('btnBatchPrev'); const next=document.getElementById('btnBatchNext'); if(prev) prev.disabled=batchPage<=0; if(next) next.disabled=(batchPage+1)>=totalPages; }

    window.addEventListener('focus', function(){ if(pendingBatchRefresh){ pendingBatchRefresh=false; if(document.getElementById('mdlSelectBatch')?.classList.contains('show')) loadBatchPage(); }});

    document.addEventListener('click', function(e){
        if(e.target?.id==='btnBatchPrev'){ batchPage--; if(batchPage<0) batchPage=0; loadBatchPage(); }
        if(e.target?.id==='btnBatchNext'){ batchPage++; loadBatchPage(); }
        if(e.target?.id==='btnMdlFilterBatches'){ batchPage=0; loadBatchPage(); }
        if(e.target?.id==='btnMdlClearBatches'){ document.getElementById('mdlBatchFilterBatchNo').value=''; const f=document.getElementById('mdlBatchFilterFunctionId'); if(f) f.value=''; batchPage=0; loadBatchPage(); }
        if(e.target?.classList.contains('btn-pick-batch')){ const tr=e.target.closest('tr'); const batchNo=tr.children[0].textContent.trim(); const batchId=tr.children[3].textContent.trim(); if(currentBatchInput){ currentBatchInput.value=batchNo; currentBatchInput.closest('tr').children[8].textContent=batchId; } bootstrap.Modal.getInstance(document.getElementById('mdlSelectBatch')).hide(); }
        if(e.target?.id==='btnNewBatch'){ if(createBatchUrl){ batchWindow=window.open(createBatchUrl,'_blank'); if(batchWindow) pendingBatchRefresh=true; }}
        if(e.target?.id==='btnMdlLoadGRN'){ grnPage=0; loadGRNList(); }
        if(e.target?.id==='btnGrnPrev'){ grnPage--; if(grnPage<0) grnPage=0; loadGRNList(); }
        if(e.target?.id==='btnGrnNext'){ grnPage++; loadGRNList(); }
        if(e.target?.classList.contains('btn-pick-grn')){ const id=e.target.getAttribute('data-id'); const code=e.target.getAttribute('data-code')||''; const input=document.getElementById('DocumentReferenceNo'); if(input) input.value=code; loadGRNItems(id); bootstrap.Modal.getInstance(document.getElementById('mdlSelectGRN')).hide(); }
        if(e.target?.id==='btnMdlFilterItems'){ itemPage=0; loadItemsForBrowse(); }
        if(e.target?.id==='btnMdlClearItems'){ document.getElementById('mdlItemFilterCode').value=''; document.getElementById('mdlItemFilterName').value=''; itemPage=0; loadItemsForBrowse(); }
        if(e.target?.id==='btnItemPrev'){ itemPage--; if(itemPage<0) itemPage=0; loadItemsForBrowse(); }
        if(e.target?.id==='btnItemNext'){ itemPage++; loadItemsForBrowse(); }
        if(e.target?.classList.contains('btn-pick-item')){ const tr=e.target.closest('tr'); const code=tr.children[0].textContent.trim(); const name=tr.children[1].textContent.trim(); const uom=tr.children[2].textContent.trim(); const itemId=tr.children[5].textContent.trim(); if(currentItemEditInput){ const row=currentItemEditInput.closest('tr'); currentItemEditInput.value=code; row.querySelector('input[name="ItemName"]').value=name; row.querySelector('input[name="UOM"]').value=uom; row.children[7].textContent=itemId; const delBtn=row.querySelector('.btn-delete-line'); if(delBtn) delBtn.disabled=false; ensureLastEmptyRow(); } bootstrap.Modal.getInstance(document.getElementById('mdlSelectItem')).hide(); }
        if(e.target?.id==='btnSelectDocRef'){ grnPage=0; loadGRNList(); new bootstrap.Modal(document.getElementById('mdlSelectGRN')).show(); }
        if(e.target?.id==='BtnSave'){ if(!saveUrl) return; if(!validateForm()) return; ChangeSaveButtonState(true); if(window.showProgressLoading) window.showProgressLoading(null,'Saving quality request. Please wait...'); const model=collectModel(); const isCreate = !model.QualityRequestId; fetch(saveUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},body:JSON.stringify(model)}).then(r=>r.json()).then(res=>{ if(window.dismissProgressLoading) window.dismissProgressLoading(); ChangeSaveButtonState(false); if(res && res.ExecutionResultId===1){
                // Success
                if(isCreate){
                    // For newly created, simplest is to reload to fetch fresh version & id
                    window.location.reload();
                } else {
                    // Update: increment EntryVersion locally and update label without reload
                    const verInput=document.getElementById('EntryVersion');
                    let v=parseInt(verInput?.value||'0'); v++; if(verInput) verInput.value=v; const lbl=document.getElementById('lblEntryVersion'); if(lbl) lbl.textContent=v; 
                    // Optionally show a success alert if framework function exists
                    if(typeof DisplayUserActionAlert==='function'){ DisplayUserActionAlert(Alert_Action_Enum.Update, Alert_Type_Enum.Success, null, 'Quality request updated successfully.', null, null, null); }
                }
            } else { if(window.DisplayUserActionSaveFailureAlert){ DisplayUserActionSaveFailureAlert(null,res?.UserInformationMessageType,res?.UserInformationMessageTitle,res?.UserInformationMessageContent);} else { alert((res&& (res.UserInformationMessageContent||res.UserInformationMessage))||'Save failed'); } } }).catch(_=>{ if(window.dismissProgressLoading) window.dismissProgressLoading(); ChangeSaveButtonState(false); alert('Save failed'); }); }
        if(e.target?.id==='BtnDelete'){
            ConfirmDeleteQualityRequest();
        }
    });

    // Sweet alert style confirm functions (reuse global alert helpers if available)
    function ConfirmDeleteQualityRequest(){
        const id=document.getElementById('QualityRequestId')?.value; if(!id) return; // nothing to delete
        if(typeof DisplayConfirmationAlert==='function'){
            DisplayConfirmationAlert(Alert_Action_Enum.Delete, Alert_Type_Enum.Warning, null, null, null, null, ProceedDeleteQualityRequest, null, true, null, null, null, null, 'quality request');
        } else {
            if(confirm('Are you sure you want to delete this quality request?')){ ProceedDeleteQualityRequest(); }
        }
    }
    function ChangeDeleteButtonState(d){ const b=document.getElementById('BtnDelete'); if(b) b.disabled=!!d; }
    function ProceedDeleteQualityRequest(){
        const id=document.getElementById('QualityRequestId')?.value; if(!id || !deleteUrl) return; ChangeDeleteButtonState(true); if(window.showProgressLoading) showProgressLoading(null,'Deleting quality request. Please wait...'); fetch(deleteUrl,{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},body:JSON.stringify({ QualityRequestId:id, EntryVersion: parseInt(document.getElementById('EntryVersion')?.value||'0')})})
            .then(r=>r.json()).then(res=>{ if(window.dismissProgressLoading) dismissProgressLoading(); if(res && res.ExecutionResultId===1){ const listUrl=document.getElementById('ViewQualityRequestListUrl')?.value||'/Quality/QualityRequestList'; window.location.href=listUrl; } else { if(typeof DisplayUserActionDeleteFailureAlert==='function'){ DisplayUserActionDeleteFailureAlert(res.UserInformationMessageType,res.UserInformationMessageTitle,res.UserInformationMessageContent);} else { alert(res.UserInformationMessageContent||'Delete failed'); } ChangeDeleteButtonState(false);} })
            .catch(_=>{ if(window.dismissProgressLoading) dismissProgressLoading(); if(typeof DisplayUserActionAlert==='function'){ DisplayUserActionAlert(Alert_Action_Enum.Delete, Alert_Type_Enum.Danger, null, null, null, null, null); } else { alert('Delete failed'); } ChangeDeleteButtonState(false); });
    }

    document.addEventListener('dblclick', function(e){ if(e.target?.name==='ItemCode') openItemBrowse(e.target); if(e.target?.name==='BatchNo') openBatchBrowse(e.target); });
    document.addEventListener('click', function(e){ if(e.target && (e.target.getAttribute('name')==='btnSearchItem' || e.target.closest('button[name="btnSearchItem"]'))){ const btn=e.target.closest('button[name="btnSearchItem"]'); const input=btn.parentElement.querySelector('input[name="ItemCode"]'); openItemBrowse(input);} });
    document.addEventListener('keydown', function(e){ if(e.key==='Enter' && e.target?.name==='ItemCode'){ e.preventDefault(); openItemBrowse(e.target); }});
    document.addEventListener('input', function(e){ if(e.target?.id==='DocumentReferenceNo' && !e.target.value){ disableBatchNos(false);} });

    function collectItems(){ const rows=[]; document.querySelectorAll('#tblItemDetails tbody tr').forEach(tr=>{ const code=tr.querySelector('input[name="ItemCode"]').value; const name=tr.querySelector('input[name="ItemName"]').value; if(!(code||name)) return; rows.push({ QualityRequestItemId: parseInt(tr.children[9]?.textContent||'')||null, ItemId: parseInt(tr.children[7]?.textContent||'')||null, GRNDetailId: parseInt(tr.children[6]?.textContent||'')||null, BatchId: parseInt(tr.children[8]?.textContent||'')||null, Quantity: parseFloat(tr.querySelector('input[name="Quantity"]').value||'0')||0, UnitOfMeasurementId:null, ItemRemark: tr.querySelector('input[name="ItemRemark"]').value||null, Code: code||null, Name: name||null, BatchNo: tr.querySelector('input[name="BatchNo"]').value||null }); }); return rows; }
    function collectModel(){ return { QualityRequestId: document.getElementById('QualityRequestId')?.value||null, RequestNo:document.getElementById('RequestNo')?.value||null, IsUserPreferredRequestNo: !!document.getElementById('IsUserPreferredRequestNo')?.checked, RequestDate: document.getElementById('RequestDate')?.value||null, FunctionId: parseInt(document.getElementById('FunctionId')?.value||'')||null, DocumentReferenceTypeId: parseInt(document.getElementById('DocumentReferenceTypeId')?.value||'')||null, DocumentReferenceNo: document.getElementById('DocumentReferenceNo')?.value||null, PriorityId: parseInt(document.getElementById('PriorityId')?.value||'')||null, StatusId: parseInt(document.getElementById('StatusId')?.value||'')||null, Remark: document.getElementById('Remark2')?.value||null, EntryIdentifier: parseInt(document.getElementById('EntryIdentifier')?.value||'0')||0, EntryVersion: parseInt(document.getElementById('EntryVersion')?.value||'0')||0, Items: collectItems() }; }

    document.addEventListener('click', function(e){ if(e.target?.classList.contains('btn-delete-line')){ const tr=e.target.closest('tr'); const tbody=tr.parentElement; tr.remove(); ensureLastEmptyRow(); }});

    function ChangeSaveButtonState(d){ const b=document.getElementById('BtnSave'); if(b) b.disabled=!!d; }
    function toggleRequestNo(){ const c=document.getElementById('IsUserPreferredRequestNo'); const r=document.getElementById('RequestNo'); if(!c||!r) return; if(c.checked){ r.disabled=false; r.classList.remove('disabled'); } else { r.disabled=true; r.classList.add('disabled'); } }
    function validateForm(){ let ok=true; const clear=n=>{ const el=document.querySelector(`span[data-valmsg-for='${n}']`); if(el) el.textContent='';}; const err=(n,m)=>{ const el=document.querySelector(`span[data-valmsg-for='${n}']`); if(el) el.textContent=m;}; ['RequestNo','StatusId','PriorityId','ItemLines','FunctionId'].forEach(clear); const chk=document.getElementById('IsUserPreferredRequestNo'); if(chk&&chk.checked && !document.getElementById('RequestNo').value){ err('RequestNo','Request No is required.'); ok=false;} if(!document.getElementById('StatusId').value){ err('StatusId','Status is required.'); ok=false;} if(!document.getElementById('PriorityId').value){ err('PriorityId','Priority is required.'); ok=false;} if(!document.getElementById('FunctionId').value){ err('FunctionId','Function is required.'); ok=false;} let has=false; document.querySelectorAll('#tblItemDetails tbody tr').forEach(tr=>{ if(tr.querySelector('input[name="ItemCode"]').value.trim()) has=true; }); if(!has){ err('ItemLines','Add at least one item line.'); ok=false;} return ok; }
    document.addEventListener('change', e=>{ if(e.target?.id==='IsUserPreferredRequestNo') toggleRequestNo(); }); document.addEventListener('DOMContentLoaded', toggleRequestNo);
    document.addEventListener('DOMContentLoaded', ensureLastEmptyRow); // Add empty row on initial load when editing existing items
})();

(function(){ if(window.__qrBatchMsgHook) return; window.__qrBatchMsgHook=true; window.addEventListener('message', function(ev){ if(!ev?.data || ev.data.source!=='CreateBatchNo' || ev.data.action!=='BatchCreated') return; if(document.getElementById('mdlSelectBatch')?.classList.contains('show')){ const inp=window._qrCurrentBatchInput||null; if(inp){ inp.value=ev.data.data?.BatchNo||inp.value; const fBtn=document.getElementById('btnMdlFilterBatches'); if(fBtn) fBtn.click(); } } }); })();
